// Package docs is a minimal stub so the blank import in
// internal/http/publicapi resolves at build time. The real Swagger
// docs are normally generated by `swag init`; this self-host build
// does not serve them.
package docs
